
* Introduction
uv.el provides an Emacs interface to [[https://github.com/astral-sh/uv][uv]], an extremely fast Python package installer and resolver. It uses the [[https://github.com/magit/transient][transient]] library to offer a Magit-like user experience for managing Python projects with uv.

* Features
- Initialize new uv projects (`uv init`).
- Add, remove, and manage project dependencies (main, development, optional).
- Lock project dependencies (`uv lock`).

* Prerequisites
- [[https://github.com/astral-sh/uv#installation][uv]] must be installed and accessible in your system's PATH.
- Emacs 25.1 or later.
- `transient.el` package (version 0.2.0 or later).

* Installation
The package is (not yet) available via Melpa.
It is therefore recommended to install it via the =:vc= argument:
#+begin_src emacs-lisp
  (use-package uv
    :vc (:url  "https://github.com/borgstad/uv.el")
    ;; Add other configurations here, e.g., keybindings
    :bind ("C-c u" . uv)
    )
#+end_src

* Usage
The main entry point for all uv operations is the command:
=M-x uv=

This command opens a transient buffer (similar to Magit) listing available actions based on the current context.

* Acknowledgements
This package is based on [[https://github.com/cybniv/poetry.el][poetry.el]] by Sacha Frey and contributors. Thanks for their effort.
